name: calendar_advanced
description: A calendar or date picker for Flutter projects.
version: 1.0.1
homepage: https://github.com/mobilesoftcode/calendar_advanced
issue_tracker: https://github.com/mobilesoftcode/calendar_advanced/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.18.0 <0.20.0"

  provider: ^6.0.5
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.3 <5.0.0"

flutter:
  assets:
    - assets/
